[project]
name = "gripper-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pymodbus==3.6.9",
    "pyside6>=6.10.0",
]
